"""Packs the Bluetooth ESP32's program (merged image written at 0x1000: bootloader + partitions
+ app) for the Wi-Fi ESP32 that updates it (wifi/main/radio.c): bt_image.bin (the app alone goes
through OTA, the whole image through the ROM bootloader) and bt_image.h (offset, size, MD5,
build id).
Usage: bt_image.py <merged.bin> <out dir>"""
import hashlib
import pathlib
import sys

OFFSET = 0x1000         # bootloader of the ESP32
APP = 0x10000 - OFFSET  # app partition, inside the image
APP_DESC = 0x20         # esp_app_desc_t after the image and first segment headers
ELF_SHA = 0x90          # its app_elf_sha256
BT_ID_LEN = 16          # components/espbar_wire/protocol.h

src, out = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2])
data = src.read_bytes()
data += b"\xff" * (-len(data) % 4)
desc = data[APP + APP_DESC:]
assert int.from_bytes(desc[:4], "little") == 0xABCD5432, "no app description in the image"
build_id = desc[ELF_SHA:ELF_SHA + 32].hex()[:BT_ID_LEN]  # what esp_app_get_elf_sha256() says

out.mkdir(parents=True, exist_ok=True)
(out / "bt_image.bin").write_bytes(data)
(out / "bt_image.h").write_text(
    "// Generated by ../../bt_image.py from the Bluetooth ESP32's build\n#pragma once\n"
    f"#define BT_IMAGE_OFFSET 0x{OFFSET:x}\n#define BT_IMAGE_SIZE {len(data)}\n"
    f"#define BT_IMAGE_APP 0x{APP:x}  // the app, inside the image (up to its end)\n"
    f'#define BT_IMAGE_MD5 "{hashlib.md5(data).hexdigest()}"\n#define BT_IMAGE_ID "{build_id}"\n')
print(f"bt image: {len(data)} bytes, build {build_id}")
